### ISSUE TITLE
Add addresses to url

### ISSUE THREAD

**Issue by Janekdererste** [graphhopper/graphhopper-maps#10]
Currently the url only stores the coordinates of selected points. It should also store the addresstext of points if present

**Comment by easbar** [comment]
Sorry maybe I missed this discussion, but why should we store addresstext in the url? And more generally, what should we store in the url and why? Is this related to browser history? I think being able to use the browser's back/forward buttons is useful in the current GH maps, but we probably won't be able to capture the app state in the URL entirely (not even the routing related part). To be able to 'share' routing examples I think we should add more powerful import/export functionality. See #25.

**Comment by Janekdererste** [comment]
I guess we peeked at google maps where the search boxes are filled with the address as well when the maps app is laoded with a shared url. The way it is at the moment is that only the coordinates of the selected addresses are stored in our app. If  a user now shares the url, the Search boxes will only show coordinates but not the address which were used to select the coordinates. 

I have no personal oppinion on the importance of this feature. So, we can start by storing other search properties in the url like selected profile etc. and postpone this one.

**Comment by easbar** [comment]
Ah ok I can see how this could be useful. I don't have a strong opinion about this, so let's keep it as it is now and postpone this decision (should be easy to change any time)? Btw I think in the long run I would like to support two use-cases:

1) 'quick sharing' of a route/isochrone etc., e.g. sending your friend a message that contains a GH url to find some location (like directions to your home). This is more user-related and sharing the route result is more important than preserving all details of the route request (like custom routing, algorithm etc.). Here simplicity (just copy&pasting and then clicking the link) is important.

2) Sharing the exact route request including e.g. the custom model/weighting that was used. This is for more advanced users and debugging purposes. It should be possible to import/export the exact request but in this case a dedicated textbox in some 'expert' UI is sufficient and the URL does not need to carry all the details (see #9).

Regarding the addresses I can see this could be useful for 1), but maybe it's not really necessary either.

**Comment by Janekdererste** [comment]
>  (should be easy to change any time)?
Yes. the data is in the state of the application and simply needs translation into a url parameter and vice versa

**Comment by karussell** [comment]
Maybe related to #56
