### ISSUE TITLE
Numbered markers

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#106]
When there are multiple via-points it would be useful to display numbered markers like on graphhopper.com/maps:

![image](https://user-images.githubusercontent.com/17603532/121964304-a0543500-cd6b-11eb-94cd-e8e928586320.png)

Another problem is that react-map-gl does not include the default marker we are using currently, so we need to add some kind of markers for #87 anyway. Currently we use a solution based on *.png files, but is this the right way to go or should we use svgs? https://github.com/graphhopper/graphhopper/blob/master/web-bundle/src/main/resources/com/graphhopper/maps/js/lib/leaflet_numbered_markers.js

For our route editor we use different markers as well: 

![image](https://user-images.githubusercontent.com/17603532/121965113-d8a84300-cd6c-11eb-9ba5-a5b4726a58af.png)

But I think the requirements are kind of the same: We need different colors and it should be possible to display a number. Right, @karussell?

@Janekdererste any thoughts about this?

**Comment by easbar** [comment]
Btw the mapbox gl js default marker we are currently using is somewhat 'buried' here:

https://github.com/mapbox/mapbox-gl-js/blob/50adf1cc14e5aef09099f15c5cb803eaa5f72a48/src/ui/marker.js#L113-L216

**Comment by Janekdererste** [comment]
I think we should use SVGs. We are using those markers in several other places. (The turn instructions have marker icons and it would be nice to replace the colored dots next to the addressInputs with markers as well) Using SVGs makes sure those icons appear sharp everywhere. 

Also, the color of SVGs can be set dynamically. We would therefore only need a single SVG asset and then color it with css or from js-code. This makes it easy to introduce another color if this need ever arises. 

Probably it would make sense to have a ```MarkerComponent``` somehow which manages the number and the coloring.

**Comment by Janekdererste** [comment]
> Btw the mapbox gl js default marker we are currently using is somewhat 'buried' here:

I do like the appearance of the mapbox marker a lot, by the way

**Comment by easbar** [comment]
Ok I agree :)

There is an example SVG based marker here:

https://github.com/visgl/react-map-gl/blob/4.0-release/examples/controls/src/city-pin.js

and it is used here: https://visgl.github.io/react-map-gl/examples/controls

I just think its kind of ugly :)

![image](https://user-images.githubusercontent.com/17603532/122018219-f0aab180-cdc2-11eb-9a7e-4aaa35ebd274.png)

> I do like the appearance of the mapbox marker a lot, by the way

Yes, me too :)

**Comment by easbar** [comment]
And while we are at it: What do you think about the height graph marker:

![image](https://user-images.githubusercontent.com/17603532/122024580-da9fef80-cdc8-11eb-986b-ae8a7c6530c6.png)

I think in its current form we cannot use it with the react mapbox wrapper either, and neither do I think it is particularly pretty. Should we just use the default Mapbox popup for this? Or any other ideas?

**Comment by Janekdererste** [comment]
> Hm, without further styling the default popup is also a bit ugly:

I think so too. On the other hand we can use the default pop up and find a better solution later, if you want to solve things with the react wrapper first
