### ISSUE TITLE
Profile box is empty under Safari/ios12

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#110]

**Comment by karussell** [comment]
For safari on iOS14.4.2 I see this problem too. But maybe instead of fixing it we should think about how to use our icons from old gh maps #58?

**Comment by easbar** [comment]
Under iOS 14.8.1 this works for me now. But I had to open a private window to prevent loading from the browser cache

**Comment by easbar** [comment]
Let's close here for now. Right now nobody of us is using ios12 anyway.
