### ISSUE TITLE
bbox is missing when query points are identical

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#115]
This query fails https://graphhopper.com/maps2/?point=51.338454%2C12.378639&point=51.338454%2C12.378639&profile=car
because when the start/target points are identical the response path is missing the bbox field. See also here: https://github.com/graphhopper/graphhopper-maps/pull/87#issuecomment-865210402

**Comment by karussell** [comment]
This will be (also) fixed on the server side: https://github.com/graphhopper/graphhopper/pull/2348

**Comment by karussell** [comment]
There is now no error anymore. So closing. The zoom is still to high but this is another issue #53.
