### ISSUE TITLE
Flickering/vanishing elevation detail overlay

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper-maps#134]
![grafik](https://user-images.githubusercontent.com/22315436/135608293-dab8f60d-235a-4729-b7ad-b80b6806c4a8.png)

The overlay often flickers/vanishes if i move the cursors along the graph. Leaving the colored area or if the overlay is flipped(black line moves to the right side of the overlay) seems like the main culprit.

Tested on Firefox 92.

**Comment by easbar** [comment]
> The overlay often flickers/vanishes if i move the cursors along the graph

Yes, this seems to happen when the cursor leaves the background (white) area and enters the colored/graph area (or the other way around)

> or if the overlay is flipped(black line moves to the right side of the overlay) seems like the main culprit.

Do you mean this: 
![image](https://user-images.githubusercontent.com/17603532/141062199-a5bd9dd6-be97-4e47-ae94-9b2a57494162.png)

The flag moves to the left side of the line when the cursor is far to the right. But this works without flickering on my machine.

**Comment by otbutz** [comment]
I thought that it had something to do with the orientation of the thin black line(left or right of the moving detail flag). But i think that was just a coincidence.

Small reproducible case:

https://graphhopper.com/maps2/?point=48.983014%2C12.090756&point=49.019437%2C12.104966&profile=bike&layer=OpenStreetMap

Moving my cursor in the area of 370m height between 1.50km and 2.50km doesn't render any flag for me on Firefox/Chrome.

**Comment by easbar** [comment]
I can reproduce this as well. It should be fixed by #155.

**Comment by otbutz** [comment]
I manually changed the `<svg class="heightgraph-container">` elements CSS in Firefox to `pointer-events: auto;` and can confirm that it works.

**Comment by easbar** [comment]
Fixed by #155
