### ISSUE TITLE
A left click in the map should close the context menu

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper-maps#135]
![grafik](https://user-images.githubusercontent.com/22315436/135608898-df04f2b9-2b7c-493c-a430-5783b3ef139a.png)

**Comment by easbar** [comment]
This is/was a bug in react-map-gl: https://github.com/visgl/react-map-gl/issues/1389.
#158 will 'silently' update react-map-gl from 5.3.16 to 5.3.17 which should fix the issue. Unfortunately it does not it seems...

**Comment by easbar** [comment]
But this is probably a problem in our code. I confirmed that 5.3.17 fixes the problem upstream using their "controls" demo: https://github.com/visgl/react-map-gl/tree/master/examples/controls). They use this:

```typescript
            closeOnClick={true}
            onClose={setPopupInfo}
```

and we do not use `onClose` yet. If I use this the context menu closes immediately after it was opens. Maybe this is even related to the context menu not appearing on mobile (https://github.com/graphhopper/graphhopper-maps/pull/149)

**Comment by easbar** [comment]
... or maybe not: I can reproduce another problem upstream: https://github.com/visgl/react-map-gl/issues/1389#issuecomment-965315354

**Comment by easbar** [comment]
This issue is still not fixed after #159. It's actually worse now: The context menu not only stays open when we click the map, but also when we pan the map. I'm actually undecided whether or not it should close when we move the map, but it should definitely close when we click the map.

**Comment by easbar** [comment]
Yes, this works perfectly, thanks! I tried FF + Chrome. The popup stays open when we move the map, but since it closes when we click I think this is fine (or maybe even better).

**Comment by easbar** [comment]
Sorry, I should have tried don mobile before merging. I cannot open the context menu anymore. Tried on iOS 14.8 using Safari,FF&Chrome

**Comment by easbar** [comment]
Openlayers implemented a long-press touch event for their drawing feature: https://github.com/openlayers/openlayers/issues/10904#issuecomment-693241627
Maybe this helps figuring out how we can open (and close) the context menu.

**Comment by Janekdererste** [comment]
Ah, very good. I’ll look into that.

**Comment by easbar** [comment]
> I'm actually undecided whether or not it should close when we move the map, but it should definitely close when we click the map.

Now I think it should definitely stay open when we move the map, because quite often we have to move the map a bit after opening the menu to see all the menu entries.
