### ISSUE TITLE
Sidebar height needs change

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#143]
Probably this was introduced for #13.

1. the default height is too large - too much white space

![image](https://user-images.githubusercontent.com/129644/136796454-022937ef-93d1-4609-b4d9-b2055b135e9f.png)

2. the last suggestions only show up with scrolling

![image](https://user-images.githubusercontent.com/129644/136796597-c0106419-6bff-4fba-a195-5c3be0b06238.png)

3. when too many via points exist the result will be hidden:

![image](https://user-images.githubusercontent.com/129644/136797124-ca7b5c9a-0e99-4b64-aed4-01ca6933b7c5.png)

For the last point I would prefer to have a scroll bar only for the via points not the entire sidebar. Or maybe a similar "collapsing" solution like we use for mobile?

**Comment by UnrealValentin** [comment]
> when too many via points exist the result will be hidden

Shouldn't the expected behavior be that it would expand till it reaches the bottom end of the screen before a scrollbar appears? At least that is the behavior in gmaps, I think
