### ISSUE TITLE
MapTiler rendering issue

### ISSUE THREAD

**Issue by aprilthepink** [graphhopper/graphhopper-maps#145]
## Was tested on the navi branch, dunno if master is different
The location I tested it on: http://127.0.0.1:3000/?point=51.436241%2C14.252902&profile=car&layer=MapTiler

The Maptiler map has still some problems rendering POIs which it gets from OSM. Seems like some properties aren't properly implemented. But let the screenshots speak for themselves
# How it should look AKA OSM
### Zoomed out
![image](https://user-images.githubusercontent.com/30842467/137331527-600befee-3e30-47b1-ba55-755aef1dc12c.png)
### Zoomed in
![image](https://user-images.githubusercontent.com/30842467/137331618-61dc1c77-5adf-4490-a272-f74867f832c2.png)
# Buggy MapTiler
### Zoomed out (even more than OSM)
![image](https://user-images.githubusercontent.com/30842467/137331845-34ce3de3-8da6-44b8-9332-4edd0da4fd46.png)
### Zoomed in (even more than OSM)
![image](https://user-images.githubusercontent.com/30842467/137331910-5eca49b2-4e2c-422d-ae8d-d17d1efe8952.png)

I think the problem is self explanatory, missing details, big text should disappear but it doesn't, (icons on wrong places - which is subjective) and greater steps than OSM for detail (which is also subjective to be honest).

**Comment by UnrealValentin** [comment]
for better visualisation:
a picture with both looks layered on top of each other, some POIs show others not. 
![image](https://user-images.githubusercontent.com/30842467/137387769-4da58a2e-ddc6-41da-8c48-99b34f761692.png)
Hope this helps better at understand the issue. 

The detailed POIs not appearing isn't a issue but I think a POI appearing twice is bad(?)

**Comment by Janekdererste** [comment]
Hi @UnrealValentin, we use the MapTiler data as is. Which POIs are shown where is not decided by us. If you are unhappy with their representation of the underlying OSM data you could get in touch with the MapTiler people. There is nothing we can do about this.
