### ISSUE TITLE
Dev deployments are broken

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#152]
For example here:

http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/93_bug_longpress/

![image](https://user-images.githubusercontent.com/17603532/140278347-62c54e3c-ed55-4c5f-800d-2b9a09973c6b.png)

**Comment by easbar** [comment]
But this works for some reason:

http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/master

**Comment by karussell** [comment]
When did you run the travis build? I fixed this yesterday:
https://github.com/graphhopper/graphhopper-maps/issues/147

**Comment by easbar** [comment]
Ah sorry I did not see #147 . Yes now it is fixed.
