### ISSUE TITLE
No routes are calculated for URLs missing the profile

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#154]
Open this URL: https://graphhopper.com/maps2/?point=52.583872%2C13.311565&point=52.475677%2C13.437286

Note that the points are specified, but no profile is given. We see two markers, but no route is calculated. The default profile is chosen and even added to the URL. We then need to refresh the page (or similar) to calculate the route. Not sure if this is a bug or a feature? It certainly seems a bit inconsistent, because reloading the page does not give the same result.

**Comment by easbar** [comment]
I think we should fix this, also because there are many URLs like this in old forum discussions etc. that did not require the `profile` parameter for the route to be calculated.

**Comment by karussell** [comment]
IMO this is a bug.

> also because there are many URLs like this in old forum discussions etc. 

(likely most URLs there still use the deprecated `vehicle` parameter where we could implement a simple rewrite :) )

**Comment by easbar** [comment]
> where we could implement a simple rewrite :) 

This is true. So basically we need to support two different kinds of legacy requests: 

1) no profile -> use the default profile (what we do already, but without having to refresh the browser)
2) no profile, but a vehicle parameter -> use the vehicle to set the `profile`.

**Comment by Janekdererste** [comment]
I want to do this issue. I can put the vehicle parameter into the parsing logic as well for now. Then nothing has to be done on the server side.

**Comment by easbar** [comment]
> I want to do this issue. I can put the vehicle parameter into the parsing logic as well for now. Then nothing has to be done on the server side.

Hm, I'm afraid it is a bit more complicated than this. There is also the related `weighting` parameter, e.g. requests using `vehicle=car&weighting=short_fastest` or `vehicle=car&weighting=fastest`. So far we were able to handle this on the server-side (where we have to handle it anyway), because the old maps client simply forwards all the url parameters. 

The first thing we should fix is the missing route calculation when the `profile` parameter is empty. 
The second thing we could do is use `vehicle` as an alias for `profile` (because it is simple enough and probably yields useful results for many legacy URLs).
But this still won't resemble the exact behavior of the old maps client. However, I am not sure if this should be our goal, so let's postpone this. @karussell ?

**Comment by karussell** [comment]
> But this still won't resemble the exact behavior of the old maps client.

I don't think this should be our goal. But we should support at least the vehicle parameter for now, yes.
