### ISSUE TITLE
Migrate from Mapbox to OpenLayers

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#159]
Still not decided whether or not we should do this, but if yes we should probably do it soon. 

Some pros and cons compared to Mapbox (just considering the issues we ran into so far)

**Pro**:

* faster raster tile rendering
* no blurry raster tiles (#156) when `constrainResolution` is enabled
* very active development compared to Mapbox, which is only developed under a proprietary license now
* was able to fix the long press issue on iOS
* (minor) commented out layers seem to work out of the box (#57)

**Con**:

* slower vector tile rendering (important for /spt, not so much for /mvt)
* if we consider vector tiles to be too slow with OL we cannot take advantage of some of the corresponding benefits, like custom map styling. Still we could use the Mapbox GL JS integration of OL.
* cannot pitch/tilt the map -> try PerspectiveMap extension

I started to explore this migration here: https://github.com/graphhopper/graphhopper-maps/tree/ol_exp 
The live instance is running here: http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/ol_exp/
See also the discussion here: https://github.com/graphhopper/graphhopper-maps/issues/132

This is the current list of todos for the ol_exp branch:

* [ ] fix remaining svg marker issues, see commit message: f2213e24e457ca90b56ce2e5ae01370abbbf116c, but at least the cursor appearance is now fixed
* [x] make markers draggable
* [x] add context menu (including the long touch handler)
* [x] put back path details layer
* [x] add map attributions
* [x] allow click selection of the paths
* [ ] restrict map zoom/pan so we cannot pan around the globe
* [ ] put back view store test
* [x] use same mouse cursors for map as in master
* [ ] bug/issue: when refreshing map with a route the map flickers and sometimes even ends up being zoomed out all the way to world view -> this is caused by a bug in master (#162)
* [ ] test (also on mobile)

**Comment by easbar** [comment]
I also tried a different way to handle the map state that could be also useful even if we kept using Mapbox (and replace the react wrapper): Basically I treat the map more like a 'store' rather than a UI component. The map object has the map state (like the camera position etc.) and is created once in `MapStore`. Then there is the `MapComponent` which is the actual UI component representing the map. It uses the map from `MapStore` and (more or less) only attaches it to a div container. The map layers are separate react components that also depend on the `MapStore` so they can attach the corresponding layers and (hopefully soon) also interaction handlers to the map. See `BackgroundLayer` for example. Actions that are supposed to change the camera position like `SetSelectedPath` are handled in the `reduce` function of `MapStore` where we have direct access to the map view. This way there is no need to manage the camera state outside of the map as we currently do in `ViewportState` in master. Not entirely sure about this yet, but so far it seems pretty useful and it certainly feels better to deal with the map directly instead of using a wrapper like `react-map-gl` that we do not really understand :) Will be interesting to see if this concept also allows easily adding click interactions for the different map layers.

**Comment by easbar** [comment]
> I think this is comparable to the Qwant people, where the map component lives outside of the react app. It listens for custom events which are issued by the react app and updates the map accordingly. This could be seen, in our case, as a store with a visual output.

Ok, interesting. I did not really check the Erdapfel code, but does this pattern make sense to you?

**Comment by Janekdererste** [comment]
> but does this pattern make sense to you?

Actually I don't really know yet. I think I would maybe not make it an actual store but we can pass other types than stores to the Dispatcher as well. So one could still listen for actions and update the internal map state accordingly. Let's talk it through via phone :-)

**Comment by boldtrn** [comment]
Thanks for providing both versions to compare. 

In Firefox (also with V94) the vector tile rendering, both of Mapbox and OL weren't great. I personally think Mapbox performs better, but both are far from great :(

In Chrome, Mapbox performs a lot better. Mapbox works without any real issues and is fun to use. OL still feels clunky, freezes sometimes for a short period. 

I tested a three different devices, all with the same result. 

> no blurry raster tiles (Blurry appearance of raster tiles #156) when constrainResolution is enabled

This might have been fixed with the latest version of Maplibre: https://github.com/maplibre/maplibre-gl-js/pull/637

**Comment by easbar** [comment]
Thanks for testing!

> In Chrome, Mapbox performs a lot better. Mapbox works without any real issues and is fun to use. OL still feels clunky, freezes sometimes for a short period.

Yes, same for iOS/Safari on my phone. With OL the vector tiles aren't really nice to use. Then again we noticed earlier that Maptiler seems to be much slower than Mapbox (at least for the styles we use). But anyway Mapbox is clearly faster for the vector tile providers we currently use (Mapbox+Mapilion). And by 'faster' I mean faster when zooming & panning the map (this is what I just tried). That does not say the initial page load (#132) is fast. This is currently hard to test, because of #162.

> This might have been fixed with the latest version of Maplibre: maplibre/maplibre-gl-js#637

But isn't this only about high-resolution tiles? The blurry tiles I was referring to in that issue were just the normal tiles from openstreetmap on my Laptop.

So yes, one important factor to decide whether we should use Mapbox or Openlayers is whether or not we should/want to use vector tiles for the map background. If you ask me we don't need this and can just go with raster tiles and OpenLayers. Or at least I haven't heard any major arguments that convinced me that vector tiles are important ;)

**Comment by boldtrn** [comment]
> And by 'faster' I mean faster when zooming & panning the map (this is what I just tried). That does not say the initial page load (#132) is fast.

Yes, that's what I was referring to as well, good to clarify.

> But isn't this only about high-resolution tiles? The blurry tiles I was referring to in that issue were just the normal tiles from openstreetmap on my Laptop.

I think raster tiles are just images that are shown on the screen. So to "fix" blurry images there are two options. Either you use high-res tiles or you load more tiles (like going one zoom level up and loading 4x the tiles). I think OSM isn't offering high-res tiles at the moment. 

> If you ask me we don't need this and can just go with raster tiles and OpenLayers.

Yes sure, if you don't need vector tiles, then I would go with OpenLayers or Leaflet straight away, no need to add hundreds of kb of dependencies and more complicated API if you don't need it :). Maplibre/Mapbox is vector tiles first.

**Comment by karussell** [comment]
> Either you use high-res tiles or you load more tiles

I think maplibre/mapbox has the problem that fractional zooms are accepted for raster tiles and there seems to be no option to disable this, so they will be blurry even if high res.

**Comment by easbar** [comment]
Yes exactly. The tiles can be blurry because they are, well, blurry. Or they can **become** blurry when they are shown at the wrong resolution. This happens for example when they are over-zoomed. For OpenLayers the `constrainResolution` option prevents the over-zooming and only uses the (discrete) zoom levels for which there are tiles.

However, the bluriness issue seems to be different on mobile. I feel like the OSM tiles (no 2x) are a bit blurry on my iPhone. I thought this is because of the high resolution of my phone's screen. But for some reason the 'Kurviger Liberty' tiles also seem blurry on my phone (for the OL branch). On master/Mapbox this is not the case, and neither for GH maps/Leaflet. @boldtrn maybe you know why this is? Maybe we are missing some settings still?

**Comment by boldtrn** [comment]
> I think maplibre/mapbox has the problem that fractional zooms are accepted for raster tiles and there seems to be no option to disable this, so they will be blurry even if high res.

Ah yes, fractional zooms might be indeed the source of this.

> But for some reason the 'Kurviger Liberty' tiles also seem blurry on my phone (for the OL branch).

Have you enabled the x2 option? Kurviger Liberty is available as high-res tiles.

**Comment by easbar** [comment]
> Have you enabled the x2 option? Kurviger Liberty is available as high-res tiles.

Yes, I thought so:

https://github.com/graphhopper/graphhopper-maps/blob/29f749b507129f5d7faa5f8723113cb0245b7d30/src/stores/MapOptionsStore.ts#L123-L137

Or is there anything else we need to do? Do we need to use the `tileSize` option for the OL View?

**Comment by boldtrn** [comment]
The url seem correct :). I am not sure if you need to set anything else in OL.

**Comment by easbar** [comment]
Ok thanks we need to check this.

This is how Kurviger Liberty currently looks using OpenLayers on my iPhone:

![image](https://user-images.githubusercontent.com/17603532/142607873-69c5cc06-751f-4543-88b9-40af9649eb34.png)

And this is how it looks on Mapbox:

![image](https://user-images.githubusercontent.com/17603532/142608097-7199e658-2c41-4aca-b7e2-7adee6cbed29.png)

For Leaflet/GH maps 1: it is even slightly better (maybe):

![image](https://user-images.githubusercontent.com/17603532/142608206-e6bae7e5-c9bd-4001-ab88-0cdb646f8541.png)

The OSM tiles are looking perfect on my Laptop, but not as nice on my phone, not even for GH maps 1:

![image](https://user-images.githubusercontent.com/17603532/142608404-1d7a33ca-31c7-4b06-bb12-7919d8917683.png)

**Comment by easbar** [comment]
@boldtrn OL has this `tilePixelRatio` option:

> The pixel ratio used by the tile service. For example, if the tile service advertizes 256px by 256px tiles but actually sends 512px by 512px images (for retina/hidpi devices) then tilePixelRatio should be set to 2.

When I set this to `2` the tiles look sharp on my phone, see here: http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/ol_exp_tile_size/?profile=bike&layer=Kurviger+Liberty
Can you comment on the tile size and pixel ratio of the Kurviger Liberty tiles?

**Comment by boldtrn** [comment]
> The pixel ratio used by the tile service. For example, if the tile service advertizes 256px by 256px tiles but actually sends 512px by 512px images (for retina/hidpi devices) then tilePixelRatio should be set to 2.

When you add @2 to the Kurviger Liberty URL, tiles are 512x512. If don't add the @2 they are 256.

**Comment by easbar** [comment]
> Actually I don't really know yet. I think I would maybe not make it an actual store but we can pass other types than stores to the Dispatcher as well. So one could still listen for actions and update the internal map state accordingly. Let's talk it through via phone :-)

I did this for #176

**Comment by easbar** [comment]
Closing here in favor of #176
