### ISSUE TITLE
Display path details without elevation data

### ISSUE THREAD

**Issue by otbutz** [graphhopper/graphhopper-maps#172]
It would be nice to have the graph also available for debugging purposes even if no elevation data is present.

![image](https://user-images.githubusercontent.com/17603532/111612467-c6565180-87dd-11eb-9440-5256c2ce07bd.png)

e.g display a flat 0m graph with color gradient for `elevation=false` + `debug=true` + `details=`

**Comment by karussell** [comment]
Here is a workaround patch where I got it working for a graphhopper setup without elevation: https://gist.github.com/karussell/b28d5dbaed9dbb62748499226d7f6463 (the surface part is a different issue)
