### ISSUE TITLE
Position of marker relative to map changes when zooming

### ISSUE THREAD

**Issue by michaz** [graphhopper/graphhopper-maps#185]
Zoomed in: North of freeway
![Screenshot 2022-03-24 at 15 06 59](https://user-images.githubusercontent.com/520916/160018232-b23dc71e-9975-4b42-ae5b-9be44558dfa3.png)

Zoomed out: South of freeway
![Screenshot 2022-03-24 at 15 07 06](https://user-images.githubusercontent.com/520916/160018244-e66cf707-ac0f-475b-a26a-4aedccde5f85.png)

**Comment by easbar** [comment]
#179, #184

**Comment by michaz** [comment]
Oh.

**Comment by easbar** [comment]
@Janekdererste did you already have time to take a look at #184 or try the OpenLayers Overlay approach?

**Comment by easbar** [comment]
Fixed in #184.
