### ISSUE TITLE
Removing package-lock.json

### ISSUE THREAD

**Issue by CutestNekoAqua** [graphhopper/graphhopper-maps#197]
It might be smart to remove the package-lock.json as it serves more as a integrity check for currently installed packages and most open-source projects keep it out of their repository for that reason. All needed packages should be in the package.json anyways and it causes problems version-vise if for example person A uses node 14 and person B node 16, for example, if they share the same package-lock.json as there are some things which node 16 adds to the lock-file which makes it unusable for the older version. Some people also prefer using yarn over npm, which also works perfectly fine and is interoperable if only the package.json is shared. The only thing which needs to be checked is, that the package.json contains every info needed for it to work.

I already tested it and it works perfectly fine on a fresh install to run npm install without a package-lock.json existing

Projects as example who not serve the package-lock.json:
https://gitlab.com/decebal2dac/pdf-page-counter
https://github.com/alfateam/a
https://github.com/caseycesari/geojson.js
https://github.com/facebook/react

**Comment by easbar** [comment]
I think it makes sense to keep the file for application type projects (like this one) and maybe leave it out for library type projects (like react). package.json does not include all packages, because it does not include packages that are required by packages listed there. It is true that the package-lock.json format, and to be more precise, the lockfileVersion changes from 1 to 2 between npm 6 and 8. This is why we recommend an explicit node/npm version to use with this project in our README.md file. We could still consider upgrading this version, but the last time we tried this we ran into some issues: https://github.com/graphhopper/graphhopper-maps/pull/158
So honestly, I'm not sure if this is worth it. Did you encounter any problems with the versions specified in README.md?

**Comment by CutestNekoAqua** [comment]
I didn't encounter direct problems with the old version but its a anti-pattern to lock users to a specific version of a tool. Especially as there are reasons why software gets updated. Like I wrote, there is currently no reason to keep the lock file around as the packages which are required by other packages are automatically downloaded. NPM handles that automatically and creates a lock file which matches your version. Without a lockfile users also aren't limited to a specific version of npm or node. Both npm 6 and npm 8 work fine then.

**Comment by easbar** [comment]
I agree it seems problematic that the lock file format changed and causes this incompatibility, but there is nothing we can do about it. I did not follow this, but there was probably some reasoning behind this.

> Like I wrote, there is currently no reason to keep the lock file around as the packages which are required by other packages are automatically downloaded.

The lock file fixes the versions of the dependencies of our dependencies to make the build fully reproducible. The node.js docs still recommend putting it under version control: https://nodejs.dev/learn/the-package-lock-json-file

> Without a lockfile users also aren't limited to a specific version of npm or node. Both npm 6 and npm 8 work fine then.

I think we ran into issues on different systems using npm 8 no matter whether there was a lock file or not (see #158). So I don't think it is a drawback to fix the specific node/npm version we use. Currently there are less than five people working on this project so I think the easiest we can do is just using the same setup. Using different node versions on the same system is very easy using nvm.

**Comment by CutestNekoAqua** [comment]
> The lock file fixes the versions of the dependencies of our dependencies to make the build fully reproducible. 

package.json can do that too

> I think we ran into issues on different systems using npm 8 no matter whether there was a lock file or not (see https://github.com/graphhopper/graphhopper-maps/pull/158). 

the errors I can see there were **because** y'all tried to use the same package-lock.json but it seems in the version you tried it on, the package-lock.json had some differences between linux and windows. I can't comment on windows as I use linux but it seemed like y'all didn't try without a package-lock.json on npm i, but with different ones. 

When there are 5 people working on the project its not the end of the world to fix it to oen package-lock.json but it would still be nice to keep this up for discussion :)

**Comment by easbar** [comment]
> package.json can do that too

No. See the docs: https://nodejs.dev/learn/the-package-lock-json-file 

> the errors I can see there were because y'all tried to use the same package-lock.json but it seems in the version you tried it on, the package-lock.json had some differences between linux and windows. I can't comment on windows as I use linux but it seemed like y'all didn't try without a package-lock.json on npm i, but with different ones.

I don't remember exactly, but I am pretty sure we tried both with and without the lockfile, this went on for a couple of days. This is also part of the reason why I do not feel like spending more time on this stuff.

> When there are 5 people working on the project its not the end of the world to fix it to oen package-lock.json but it would still be nice to keep this up for discussion :)

I'm trying to stay open, but I think we had this discussion already and I see no reason to remove the file so far. I think all you need to do is use the npm version mentioned in the readme and we can move on :D

**Comment by easbar** [comment]
Related: #205
