### ISSUE TITLE
extra zoom buttons on map

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#234]
This could help to better control the zoom for certain hardware, where the "touch zoom gesture" produces too big zoom changes (it was observed on a Macbook Air)

**Comment by easbar** [comment]
It might be possible to configure the zoom sensitivity so it does not zoom as fast. But extra buttons are also helpful for one-handed zooming (e.g. when riding a bike and holding a phone with one hand).

**Comment by easbar** [comment]
Currently it is also possible to double-click the map to zoom in by a fixed amount.
