### ISSUE TITLE
initial history should not be created for start page

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#259]
Currently if you go to https://www.graphhopper.com/ then click "maps" the back button will only remove the profile parameter.

Instead it should go back to www.graphhopper.com/

Maybe we should not add parameters for the start page?

**Comment by easbar** [comment]
Can we not open maps in another tab when we click 'maps' on graphhopper.com? 

This aside it looks like we need to adjust the code in NavBar such that when we open a maps url and do some automatic modification like adding the profile no extra state is pushed to the window history. Did you try this yet?

**Comment by easbar** [comment]
> Yes, sure. But I still think the current behaviour is wrong :)

Yes, the current behaviour is wrong indeed. I just thought that opening in a new tab would be better than keeping the same anyway, and the easiest possible 'fix' for the present issue.

> I didn't find a solution on how to find out the right time when/how to enable history again.

I'll have a look. NavBar already has this strange isIgnoreQueryStoreUpdates flag added for #92 which looks like it is supposed to prevent calling `window.history.pushState` while we parse the url initially, but there are still multiple states added to the history:

```
http://localhost:3000/?profile=&layer=OpenStreetMap 
http://localhost:3000/?profile=car&layer=OpenStreetMap
http://localhost:3000/?profile=car&layer=OpenStreetMap (a second time)
```

So we are setting up a listener that updates the window history every time the app state changes, but then we realize we don't want this while parsing the url and invent a flag that is supposed to prevent this temporarily. And now we realized it is not working as expected for some reason and a solution would be to modify the state only in a way such that it does work (leave out profile and layer). But really I think it should work as follows:

* parse the url, no listeners yet
* setup the listener such that from now we get a new history entry when app state changes yield a new url

**Comment by easbar** [comment]
> but there are still multiple states added to the history:

This is because of two *asynchronous* events: MapIsLoaded and InfoReceived. So the `isIgnoreQueryStoreUpdates` thing does not work because it blocks the window history updates synchronously, but when the map has finished loading and the /info request returns we still push new window history states (without any user interaction).
