### ISSUE TITLE
GPX export - not only GPX track export possible

### ISSUE THREAD

**Issue by devnull4242** [graphhopper/graphhopper-maps#260]
In the old version of  Graphhopper e.g. https://graphhopper.com/maps there was the possibilty to export different type. I think there was almost **GPX route** and **GPX track**

Now i get with "Export GPX" an GPX file with waypoints, route and track.  I must delete the not needed parts (for me wpt and rte on my own).
```
<wpt> </wpt>
<rte></rte>
<trk></trk>
```
Can you implement the old function to differ GPX exports between waypoints, route and track?

**Comment by devnull4242** [comment]
Sorry. Thanks for issue tracker `tracker graphhopper-maps/issues`

Yes there is a problem. If i use the output on a web based gpx viewer (e.g. https://j-berkemeier.de/ShowGPX.html ). Also if i use it on my Android device in the app OSMAnd. 

Sorry i do not know the old version of **graphhopper-maps**. Maybe you can look in an old version (few weeks ago all was ok). There was a possibilty after click on "GPX" there was an option to activate "route" or "track". There you get only parts of the full GPX informations (e.g. rte or trk).

**Comment by ratrun** [comment]
I also would like to have this functionality back. My old [arguments from](https://github.com/graphhopper/graphhopper/issues/310#issuecomment-145385325)  the functionality about the Garmin tools and devices] are still valid. Here is the relevant part:

> I'm using a Garmin GPS. Waypoints are places, which are displayed on the map with an icon. Until now, I always had to remove the route part by hand. The turn instructions messed up the way points on the device, as it also generates a separate place point entry for every turn. As a consequnce you see nearly nothing except icons. And manual deletion of tlhe place point on the smal device is a real pain. Therefore, I think that by putting only the start, the via and the endpoint to the waypoints toghether with the possiblity to select "track" or "route" export allows the biggest flexibility for the end users, which we should reasonably support. If further flxibility is needed (e.g. remobval of elevation), the user always can use separate tools as e.g. gpsbabel.

Unfortunately this time I won't be able to provide a PR because I'm not (yet?) familiar with react/typescript. (😢 )

**Comment by ratrun** [comment]
> And what if we for now only include the trk entries until someone provides a better solution with a dialog or some settings?

Yes, I aleardy did this in my branch. I cannot predict how many users might miss the waypoints or the route functionality, but I expect fewer complaints in comparison with the current behaviour. And it was the default setting.

**Comment by ratrun** [comment]
Thank you, this looks good and it works as expected!

**Comment by devnull4242** [comment]
That solves all my problems. Now i get back the track that i and i think the most users only need from gpx export. In web gpx viewer e.g. https://j-berkemeier.de/ShowGPX.html all looks fine. And the navigation along the track with OSMAnd also works wonderfully. 

Thank you very much for this nice software and the rapid optimization of the software.

**Comment by MF29091959** [comment]
Hello, now i miss the functionality to export the waypoints and the details in the gpx file. Only track are available. I need all, waypoints, details and tracks. Please add this functionalities as it was in the old graphhopper maps.. Thank you.
