### ISSUE TITLE
Improve linking to a single location

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#304]
Currently we can link to a location by using a single `point` argument: https://graphhopper.com/maps/?point=berlin and it will already do the geocoding automatically.

Still, there are important improvements:

 - [x] zoom closer and zoom also when a location is selected from the suggestion (via mouse or ENTER)
 - [x] avoid that the first point is remove so that destinations can be specified: https://graphhopper.com/maps/?point=&point=berlin

**Comment by flaun** [comment]
would be nice to have this!
very often I use graphhopper maps just by showing me a single point without a route.
thx for your work!
