### ISSUE TITLE
Add cyclosm map layer?

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#317]
Some might find it more detailed than Thunderforst: https://tools.geofabrik.de/mc/#14/47.2622/11.4024&num=2&mt0=cyclosm&mt1=thunderforest-cycle
E.g. house numbers are included.

**Comment by apophenic-treehugger** [comment]
To elaborate a bit:

At [low zoom](https://tools.geofabrik.de/mc/#12/46.0639/14.5124&num=2&mt0=cyclosm&mt1=thunderforest-cycle) levels, cyclosm shows:
- cycle paths
- altitude lines
- clearer colours

At [high zoom](https://tools.geofabrik.de/mc/#18/46.0530/14.5118&num=2&mt0=cyclosm&mt1=thunderforest-cycle) levels cyclosm shows:
- **oneway**-restrictions on cycle tracks
- **access restrictions** on carriageways (colour-coded)
- **traffic lights**
- **housenumbers**
- capacity of bicycle **parking**
- **rest places** like benches (z>=19, not accessible in map compare) and picnic tables
- **natural features** like scrub, grass, trees, embankments
- **amenities** like supermarkets, bakeries, cafes, 
- **accomodation** like hotels, hostels, camp sites (e. g. [here](https://tools.geofabrik.de/mc/#14/46.0931/14.5175&num=2&mt0=cyclosm&mt1=thunderforest-cycle))

For transparency: I'm the one who suggested to @karussell to include a cyclosm layer. I'm not affiliated with cyclosm (which is free anyways). I'm just a volunteer openstreetmap [contributor](https://hdyc.neis-one.org/?martianfreeloader) and a passionate cyclist. I love the Graphhoper routing web interface as it is a simple, useful and fun tool that makes great use of the free-time mapping work of myself and many, many others. I'm already promoting it to friends. Adding a cyclosm layer would -- in my opinion -- make it even more appealing.

**Comment by easbar** [comment]
There seems little reason not to add it? I also think it looks very nice.

**Comment by apophenic-treehugger** [comment]
From my perspective, the Openstreetmap.de layer doesn't appear to offer much added value as it differs from the standard openstreetmap (carto) layer only by the colouring scheme of main roads and motorways, as far as I can tell.
