### ISSUE TITLE
"Recalculate the current route based on current position"-Button

### ISSUE THREAD

**Issue by SachsenspieltCoding** [graphhopper/graphhopper-maps#349]
Currently you have the following problem: You have created a route from your current position to a certain destination. Now you put your mobile phone away and start walking. After a certain time, you want to see how long it will take or how far the destination is away, but there is a problem. There is no way to recalculate the route based on the current location. In order to achieve this, you must first enter a fixed POI/address as the starting point before the new coordinates are taken over for the current location. I think this is also related to how the app handles the current location.

I would like to see a kind of "Recalculate" button that updates the current location once and recalculates the route based on this.

**Comment by easbar** [comment]
Related: #337

**Comment by SachsenspieltCoding** [comment]
> Related: #337 

Ah yes, I must have overlooked it. Having an autocomplete item in the ‘from’ input is probably even better since it is more straightforward.
