### ISSUE TITLE
Create better layout for mobile/small screens

### ISSUE THREAD

**Issue by Janekdererste** [graphhopper/graphhopper-maps#44]
The current approach looks good on large window sizes but takes up too much space on small screens.

- The logo needs too much space (I think it takes up too much space in every case)
- Route alternatives are displayed as rows. This takes too much horizontal screen space
- The search box itself takes up too much space especially when more via points are displayed
- close or hide elevation widget

**Comment by karussell** [comment]
For mobile I looked how others (qwant, google, ...) did this and I think the most important aspect is that the map should be as large as possible :D 

And e.g. when clicking on the input the rest of the panel can disappear (maybe even the map). The tricky thing is the alternatives and the vehicle options. I solved it here using an "expandable row" e.g. clicking on the "alternatives" shows all alternatives in one row below and similar for the vehicles and options. The alternatives could be even omitted (not sure if that is good UX) when we assume the user knows how to click on the "1 circle" or "2 circle" on the map. Additionally if the screen is still too small I put a fullscreen icon below or we could use full screen as soon as the map is dragged or something.

![image](https://user-images.githubusercontent.com/129644/112974012-3f489800-9152-11eb-805e-4e0d56b9dd63.png)

**Comment by karussell** [comment]
Should we show the logo only when we type the location? (and/or remove the "maps" text of the logo? and/or move "GraphHopper" into the copyright text of the map?)

**Comment by Janekdererste** [comment]
Elevatio Plugin should not be displayed on small sceens

**Comment by karussell** [comment]
Related to #20

**Comment by Janekdererste** [comment]
![grafik](https://user-images.githubusercontent.com/8005495/115233407-28c1ab00-a118-11eb-88ae-354e7764335f.png)
Compare different routing providers on mobile

**Comment by Janekdererste** [comment]
![grafik](https://user-images.githubusercontent.com/8005495/115237753-375e9100-a11d-11eb-8381-5b675aa4d770.png)
Waze

**Comment by Janekdererste** [comment]
![21-04-19 14-36-37 0217](https://user-images.githubusercontent.com/8005495/115238084-90c6c000-a11d-11eb-9c74-648f7f80dea4.png)
iOS (Apple Maps)

**Comment by Janekdererste** [comment]
![21-04-19 14-52-28 0218](https://user-images.githubusercontent.com/8005495/115239923-87d6ee00-a11f-11eb-962e-4091f9db64f4.png)
Here maps (iOS)

**Comment by Janekdererste** [comment]
![21-04-19 14-55-45 0219](https://user-images.githubusercontent.com/8005495/115239958-92918300-a11f-11eb-9397-f79790ea0f6b.png)
Bikemap (iOS)

**Comment by karussell** [comment]
( Having the input at the bottom like HERE maps is not a bad idea. E.g. firefox mobile uses the address bar at the bottom too and once you are used to it, the bar at the top seems miles away :D )

**Comment by easbar** [comment]
> Compare different routing providers on mobile

The logo obviously takes too much space? And maybe it would be sufficient to add a single line (distance+time) for each alternative?

Btw on my iphone 5s, ios 12.4.9 the layout is broken (the add point button takes too much/all space):

![image](https://user-images.githubusercontent.com/17603532/115288327-9ccc7500-a151-11eb-9806-febfc6044814.png)

Same problem in both FF and Safari. Also it became clear that showing the auto complete suggestions below the input boxes does not work, because they are entirely hidden by the on-screen keyboard and this makes you think there are no auto completions at all.

**Comment by easbar** [comment]
Ok sure. Whatever works best. I just thought the vertical space seems more limited than the horizontal space

![image](https://user-images.githubusercontent.com/17603532/115298683-0fdbe880-a15e-11eb-90f2-4800e8607379.png)

Scrolling swiping in horizontal direction sounds good to me too.

**Comment by jguddas** [comment]
This is a mockup I had lying around of the old maps mobile view.

![image](https://user-images.githubusercontent.com/25524993/116006985-e57ea500-a60d-11eb-97ad-1efd6d12cb91.png)
