### ISSUE TITLE
Use icons instead of emojis

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#58]
I see a strange gender (?) symbol next to the vehicle icons:

![image](https://user-images.githubusercontent.com/17603532/114511850-bbee7280-9c38-11eb-8f8f-0e1478aeed5c.png)
![image](https://user-images.githubusercontent.com/17603532/114511900-c9a3f800-9c38-11eb-9ee6-b4e82ccb2001.png)
![image](https://user-images.githubusercontent.com/17603532/114511938-d294c980-9c38-11eb-8ee1-d5e7da61f3de.png)

but this only happens in Firefox. Using Chrome it looks normal, for example:

![image](https://user-images.githubusercontent.com/17603532/114512066-f8ba6980-9c38-11eb-938a-79728f13bf85.png)

**Comment by Janekdererste** [comment]
Haha, the emojis are actually gendered. I didn't see this on firefox for windows. 

Since Peter was unhappy with those anyway, I expect them to be replaced by something else.
