### ISSUE TITLE
Maps redirect to root

### ISSUE THREAD

**Issue by rokcarl** [graphhopper/graphhopper-maps#59]
When I deployed the maps on my server under `https://server.com/maps/`, I was redirected to `https://server.com/?vehicle=car`. Checking the HTTP headers I see that the redirect doesn't happen on the backend side, i.e. the request to `https://server.com/maps/` is a `200`. So this is probably happening on the frontend?

**Comment by Janekdererste** [comment]
Yes, this happens on the frontend.

The app stores the current query in the url without re-loading. If you'd select a different routing vehicle this parameter should change. You'll see more parameters once you set other parameters such as the start and end-point of a route.

The idea is that you could copy this url and get the same routing result in another browser.

**Comment by rokcarl** [comment]
I know what you mean with the history and all, but in my case, I'm not worried about the `?vehicle=car` query parameters, but the path from `/maps/` to `/`.

**Comment by Janekdererste** [comment]
Oh, I see. This is something we have to look into then. Thanks for pointing it out.
