### ISSUE TITLE
latitude and longitude are swapped compared to old maps

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#62]
Currently we have lat,lon in old GH Maps and lon,lat here. 

Of course we use `[lon,lat]` in the POST /route endpoint and so lon,lat makes a lot of sense for the input fields too, but unfortunately it would break old URLs:

https://graphhopper.com/maps/?point=51.43331%2C14.250083&point=50.909961%2C2.988736
https://graphhopper.com/maps2/?point=51.43331%2C14.250083&point=50.909961%2C2.988736

Also other services like google (or qwant or tomtom or here maps) use the order lat,lon to visualize coordinates. What should we do :D ?

**Comment by easbar** [comment]
Should we really try to keep the urls backward-compatible? Will this work also for urls that use other url parameters (that maybe won't be there in maps2 anymore)?

**Comment by karussell** [comment]
I am not sure.

**Comment by easbar** [comment]
One reason we should use lon,lat is that this would be consistent with our (post) API. Using lat,lon would be consistent with previous versions of GH maps (and other services). Not sure what is more important :) Maybe just not change anything unless there is a strong reason to change, so let's keep using lat,lon?

Btw we could also allow entering something like `lat: 50, lon: 3`

**Comment by karussell** [comment]
I have now a strong tendency to use the old `lat,lon` order (the reason of other services and avoid breaking backward compatibility) but also only then we can easily copy&paste a request to and from /route

**Comment by easbar** [comment]
> I really wonder how many years of life time this lat,lon vs. lon,lat discussion costs the world :D

If only it was the only discussion of this kind :D 

But I think I agree that keeping lat, lon is the better option.
