### ISSUE TITLE
server side timeout of alternative routes results in JS error

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#70]
error in the UI is

```
(intermediate value).hints is undefined
```

but it should better show "500 Internal Server Error" or something.

Example: https://graphhopper.com/maps2/?point=51.11452800111718%2C10.591936151781283&point=48.8588897%2C2.320041027461107&profile=foot (probably alternative route calculation takes too long for this distance.)

**Comment by Janekdererste** [comment]
I guess this could become a more general issue about error messages. So far errors are caught and an Error Action is dispatched. Then we have an Error Store, which just swallows the dispatched error message. This could be more elaborate I guess.
