### ISSUE TITLE
Problems with map style selection on firefox mobile

### ISSUE THREAD

**Issue by Janekdererste** [graphhopper/graphhopper-maps#80]
selecting a different map on mobile nearly always results in selecting kurviger first before I can open it

**Comment by Janekdererste** [comment]
@karussell I think you reported this in #74 . I can't reproduce this. I this still an issue for you? It seems like the radio button selection is not working properly?

**Comment by karussell** [comment]
Indeed this works now. Strange.

**Comment by easbar** [comment]
Maybe this was fixed by #77 (?)
