### ISSUE TITLE
Replace Mapbox GL JS with Maplibre GL JS

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#81]
code: https://github.com/MapLibre/maplibre-gl-js
docs: https://maplibre.org/maplibre-gl-js-docs/api/

especially when we hit a bug or want to be mentioned there :)

**Comment by HarelM** [comment]
+1
If you have any questions feel free to ping me. I'm one of the core contributers at maplibre :-)

**Comment by easbar** [comment]
We use OpenLayers since #159

**Comment by HarelM** [comment]
Cool!
Bare in mind that when I tested OL about two years ago the performance for vector tiles on mobile phones was very poor.
But it might not be a strong argument for you guys.
Also note that we are planning on adding terrain 3d support in maplibre in the near future which I don't think is possible in OL.
But I know OL is a solid choice :-) If I wasn't interested in vector tiles I would surely use them.
Thanks for the update.

**Comment by easbar** [comment]
Yes this was also a major decision point for us. For now we are happy to continue using raster tiles as we did in the past.
