### ISSUE TITLE
Do not show flicker/jump when map loads with route coordinates

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#82]
For example when we open the app with this url: `http://localhost:3000/?point=48.098438%2C15.203637&point=47.755246%2C17.388894&profile=car` we first see the map and then the map jumps to the route.

See also discussions in #53, #71, #77.

**Comment by karussell** [comment]
strange: when I open https://graphhopper.com/maps2 in Desktop firefox the map flicker/jump does no longer happen but it still happens in mobile firefox :( 
It appears it initially uses the correct "slightly zoomed in" world wide bbox and then it zooms out to default bbox or the /info bbox?

**Comment by easbar** [comment]
> without any route coordinates

the initial bounding box was ignored when the app loaded until #98. Since this is fixed now we see a similar problem no matter if there are route coordinates or not. The map is created with a large bounding box and then jumps to either the info box or the route box. Both cases will be fixed with #87
