### ISSUE TITLE
picking from auto completion is no longer possible

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#91]
For firefox mobile on Android only. For desktop firefox and chrome on Android it works.

I think this is since #88. 

When picking the location it does not show the marker and also does not know the resolved location.

**Comment by Janekdererste** [comment]
As well as on iOS

**Comment by Janekdererste** [comment]
Of course I didn’t really test #88 on mobile due to the lack of a real keyboard 🙄

**Comment by Janekdererste** [comment]
We also need to listen for touch cancel. Otherwise things get selected when one tries to scroll the result list for example.

**Comment by Janekdererste** [comment]
Solved this with https://github.com/graphhopper/graphhopper-maps/pull/107
