### ISSUE TITLE
Send route query again when pressing enter

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#95]
Continuing the discussion from here: https://github.com/graphhopper/graphhopper-maps/pull/88#issuecomment-853754364

> Which behaviour do we want in this case? Simply try to use the text-input's content as coordinate? Only if it has changed since the last time? Or should the Enter -> Search thing be a more global thing? Also, should the search be triggered only in case an input box is highlighted or again at any time?

Yes, I would trigger the routing request if Enter is pressed while the cursor is in one of the input boxes and either do geocoding with nominatim or, if it is a GPS coordinate use it as is (compare this comment: https://github.com/graphhopper/graphhopper-maps/issues/54#issuecomment-856893896). It should not matter whether anything changed since last time, simply send the request or is this somehow complicated? I do not think the Enter key should be global, it should be enough to have it while the focus is in one of the input boxes.

**Comment by karussell** [comment]
Currently this does not work if auto complete box is not yet shown.
